services:
  typesense:
    image: typesense/typesense:0.25.1
    container_name: typesense-server
    restart: always
    command: '--data-dir /data --api-key=xyz123 --enable-cors'
    ports:
      - "8108:8108"
    volumes:
      # Map a local folder in the repo to /data in the container
      - ./typesense-config/data:/data