services:
  typesense:
    image: typesense/typesense:27.1
    container_name: typesense-server
    restart: always
    command: '--data-dir /data --api-key=xyz123clave_admin_secreta --enable-cors'
    ports:
      - "8108:8108"
    volumes:
      - typesense_data:/data
    environment:
      # Define tu API Key aqu√≠
      - TYPESENSE_API_KEY=xyz123clave_admin_secreta
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true

volumes:
  typesense_data:
    driver: local